"""initial schema

Revision ID: 7249ef5f3a24
Revises: 
Create Date: 2026-07-01 20:00:37.898394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7249ef5f3a24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_alert_categories_name'))
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('ping_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ping_interval_bucket', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers')),
    sa.UniqueConstraint('name', name=op.f('uq_servers_name'))
    )
    op.create_table('ssh_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ssh_keys')),
    sa.UniqueConstraint('name', name=op.f('uq_ssh_keys_name'))
    )
    op.create_table('telegram_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_bot_token', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_bots')),
    sa.UniqueConstraint('name', name=op.f('uq_telegram_bots_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('http_monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('expected_status_codes', sa.String(length=64), nullable=False),
    sa.Column('interval_bucket', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_http_monitors_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_http_monitors'))
    )
    op.create_table('node_exporter_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('ssh_key_id', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(length=64), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('install_status', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('host_key_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_node_exporter_configs_server_id_servers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['ssh_keys.id'], name=op.f('fk_node_exporter_configs_ssh_key_id_ssh_keys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_exporter_configs')),
    sa.UniqueConstraint('server_id', name=op.f('uq_node_exporter_configs_server_id'))
    )
    op.create_table('port_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('expected_state', sa.String(length=8), nullable=False),
    sa.Column('interval_bucket', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_port_checks_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port_checks'))
    )
    op.create_table('telegram_bot_categories',
    sa.Column('telegram_bot_id', sa.Integer(), nullable=False),
    sa.Column('alert_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_category_id'], ['alert_categories.id'], name=op.f('fk_telegram_bot_categories_alert_category_id_alert_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telegram_bot_id'], ['telegram_bots.id'], name=op.f('fk_telegram_bot_categories_telegram_bot_id_telegram_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('telegram_bot_id', 'alert_category_id', name=op.f('pk_telegram_bot_categories'))
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('port_check_id', sa.Integer(), nullable=True),
    sa.Column('http_monitor_id', sa.Integer(), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('consecutive_breaches_required', sa.Integer(), server_default='3', nullable=False),
    sa.Column('custom_message_template', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('consecutive_breach_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consecutive_healthy_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(rule_type = 'server_ping' AND server_id IS NOT NULL AND port_check_id IS NULL AND http_monitor_id IS NULL) OR (rule_type IN ('resource_cpu', 'resource_ram', 'resource_disk') AND server_id IS NOT NULL AND port_check_id IS NULL AND http_monitor_id IS NULL) OR (rule_type = 'tcp_port' AND port_check_id IS NOT NULL AND server_id IS NULL AND http_monitor_id IS NULL) OR (rule_type = 'http_monitor' AND http_monitor_id IS NOT NULL AND server_id IS NULL AND port_check_id IS NULL)", name=op.f('ck_alert_rules_valid_target_for_rule_type')),
    sa.ForeignKeyConstraint(['category_id'], ['alert_categories.id'], name=op.f('fk_alert_rules_category_id_alert_categories')),
    sa.ForeignKeyConstraint(['http_monitor_id'], ['http_monitors.id'], name=op.f('fk_alert_rules_http_monitor_id_http_monitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_check_id'], ['port_checks.id'], name=op.f('fk_alert_rules_port_check_id_port_checks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_alert_rules_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name=op.f('fk_alert_events_alert_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_table('alert_rules')
    op.drop_table('telegram_bot_categories')
    op.drop_table('port_checks')
    op.drop_table('node_exporter_configs')
    op.drop_table('http_monitors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('telegram_bots')
    op.drop_table('ssh_keys')
    op.drop_table('servers')
    op.drop_table('alert_categories')
    # ### end Alembic commands ###
