"""add llm cost exporter and usage tables

Revision ID: fbd5fe7be3f3
Revises: 7249ef5f3a24
Create Date: 2026-07-09 19:24:41.544768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd5fe7be3f3'
down_revision: Union[str, None] = '7249ef5f3a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cost_exporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_llm_cost_exporters_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_cost_exporters')),
    sa.UniqueConstraint('server_id', name=op.f('uq_llm_cost_exporters_server_id'))
    )
    op.create_table('llm_usage_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_write_tokens', sa.BigInteger(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_llm_usage_daily_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage_daily')),
    sa.UniqueConstraint('server_id', 'date', 'provider', name='uq_llm_usage_daily_server_date_provider')
    )
    op.create_index(op.f('ix_llm_usage_daily_date'), 'llm_usage_daily', ['date'], unique=False)
    op.create_index(op.f('ix_llm_usage_daily_server_id'), 'llm_usage_daily', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_daily_server_id'), table_name='llm_usage_daily')
    op.drop_index(op.f('ix_llm_usage_daily_date'), table_name='llm_usage_daily')
    op.drop_table('llm_usage_daily')
    op.drop_table('llm_cost_exporters')
    # ### end Alembic commands ###
